name: Push Changes to main Branch

on:
  push:
    branches:
      - main
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yaml

  scan:
    needs: publish
    uses: ./.github/workflows/scan.yaml
